-- E08 closure seed — make the CPQ schema visible in a runnable environment.
--
-- V90 created the production-grade CPQ tables, constraints, RLS and RBAC. This
-- migration populates tenant product catalogues and representative quote
-- transactions from the already-seeded opportunity price list so fresh Docker
-- environments do not expose an empty commerce workspace.

insert into cpq.product
  (tenant_id, code, name, description, product_family, category, unit_of_measure,
   is_active, is_subscription, attributes, default_cost)
select distinct e.tenant_id,
       e.product_code,
       e.product_name,
       'Seeded from the opportunity price list to bootstrap the governed CPQ catalogue.',
       case
         when e.product_code like 'PLT-%' then 'Platform'
         when e.product_code like 'MOD-%' then 'Module'
         when e.product_code like 'SVC-%' then 'Services'
         when e.product_code like 'SUP-%' then 'Support'
         else 'Commercial'
       end,
       case
         when e.recurring then 'Subscription'
         when e.product_code like 'SVC-%' then 'Professional Services'
         else 'One-time'
       end,
       e.unit_of_measure,
       e.active,
       e.recurring,
       jsonb_build_object('source', 'pipeline.price_book_entry', 'bootstrap', true),
       e.unit_cost
from pipeline.price_book_entry e
on conflict (tenant_id, code) do update
  set name = excluded.name,
      product_family = excluded.product_family,
      category = excluded.category,
      unit_of_measure = excluded.unit_of_measure,
      is_active = excluded.is_active,
      is_subscription = excluded.is_subscription,
      default_cost = excluded.default_cost,
      updated_at = now(),
      version = cpq.product.version + 1;

insert into cpq.price_book
  (tenant_id, code, name, currency_code, status, is_default, activated_at)
select b.tenant_id,
       'STANDARD-' || upper(left(replace(b.id::text, '-', ''), 8)),
       b.name,
       'USD',
       case when b.active then 'ACTIVE' else 'ARCHIVED' end,
       b.is_default,
       case when b.active then now() else null end
from pipeline.price_book b
on conflict (tenant_id, code) do update
  set name = excluded.name,
      status = excluded.status,
      is_default = excluded.is_default,
      activated_at = excluded.activated_at,
      updated_at = now(),
      version = cpq.price_book.version + 1;

insert into cpq.price_book_entry
  (tenant_id, price_book_id, product_id, unit_price, unit_cost, currency_code,
   pricing_method, effective_from, effective_to, is_active)
select e.tenant_id,
       cb.id,
       p.id,
       e.list_price,
       e.unit_cost,
       'USD',
       'LIST',
       date '2026-01-01',
       null,
       e.active
from pipeline.price_book_entry e
join pipeline.price_book pb on pb.tenant_id = e.tenant_id and pb.id = e.price_book_id
join cpq.price_book cb on cb.tenant_id = pb.tenant_id and cb.name = pb.name
join cpq.product p on p.tenant_id = e.tenant_id and p.code = e.product_code
where not exists (
  select 1 from cpq.price_book_entry existing
  where existing.tenant_id = e.tenant_id
    and existing.price_book_id = cb.id
    and existing.product_id = p.id
    and existing.is_active
    and daterange(existing.effective_from, existing.effective_to, '[]') && daterange(date '2026-01-01', null, '[]')
);

insert into cpq.approval_policy
  (tenant_id, code, name, trigger_type, applies_to, threshold_pct, margin_floor_pct,
   product_category, approver_role, priority)
select t.id, seed.code, seed.name, seed.trigger_type, seed.applies_to, seed.threshold_pct,
       seed.margin_floor_pct, seed.product_category, seed.approver_role, seed.priority
from platform.tenant t
cross join (values
  ('DISC-15-SUBSCRIPTION', 'Subscription discount above 15%', 'DISCOUNT_PCT', 'QUOTE', 15.0000::numeric, null::numeric, 'Subscription', 'SALES_MANAGER', 20),
  ('MARGIN-35-SERVICES', 'Services margin floor 35%', 'MARGIN_FLOOR', 'QUOTE', null::numeric, 35.0000::numeric, 'Professional Services', 'FINANCE', 30)
) as seed(code, name, trigger_type, applies_to, threshold_pct, margin_floor_pct, product_category, approver_role, priority)
on conflict (tenant_id, code) do nothing;

insert into cpq.document_template
  (tenant_id, code, name, brand_name, brand_tagline, accent_hex,
   intro_template, terms_template, footer_template, is_default, is_active)
select t.id,
       'STANDARD-QUOTE',
       'Standard enterprise quote',
       t.name,
       'Commercial proposal prepared in Axiom CRM',
       '#0B6E4F',
       'Thank you for the opportunity to support {{account.name}}. This proposal summarizes the current commercial offer.',
       'Prices are valid until {{quote.expires_at}} and are subject to mutually executed order terms.',
       'Generated by Axiom CRM. Quote {{quote.quote_number}}.',
       true,
       true
from platform.tenant t
on conflict (tenant_id, code) do nothing;

insert into cpq.guided_question
  (tenant_id, questionnaire, code, sequence_no, prompt, help_text, answer_type)
select t.id, 'DEFAULT', seed.code, seed.sequence_no, seed.prompt, seed.help_text, 'SINGLE_SELECT'
from platform.tenant t
cross join (values
  ('PRIMARY_GOAL', 10, 'What is the customer buying motion?', 'Guides catalogue recommendations by commercial intent.'),
  ('SERVICE_NEED', 20, 'How much implementation help is needed?', 'Helps attach services without burying them in the product list.')
) as seed(code, sequence_no, prompt, help_text)
on conflict (tenant_id, questionnaire, code) do nothing;

insert into cpq.guided_answer_option
  (tenant_id, question_id, code, label, filter_category, filter_attribute_name,
   filter_attribute_value, recommended_product_id, weight, sort_order)
select q.tenant_id,
       q.id,
       seed.code,
       seed.label,
       seed.filter_category,
       null,
       null,
       p.id,
       seed.weight,
       seed.sort_order
from cpq.guided_question q
join (values
  ('PRIMARY_GOAL', 'CORE_CRM', 'Core CRM platform', 'Subscription', 'PLT-CORE', 90, 10),
  ('PRIMARY_GOAL', 'ADVANCED_REVENUE', 'Advanced revenue operations', 'Subscription', 'PLT-ADV', 100, 20),
  ('SERVICE_NEED', 'IMPLEMENTATION', 'Implementation support required', 'Professional Services', 'SVC-IMPL', 80, 10),
  ('SERVICE_NEED', 'TRAINING', 'Enablement and training required', 'Professional Services', 'SVC-TRAIN', 70, 20)
) as seed(question_code, code, label, filter_category, product_code, weight, sort_order)
  on seed.question_code = q.code
join cpq.product p on p.tenant_id = q.tenant_id and p.code = seed.product_code
on conflict (tenant_id, question_id, code) do nothing;

with quote_seed as (
  select * from (values
    ('88888888-8888-8888-8888-888888888801'::uuid, '88888888-8888-8888-8888-888888888811'::uuid,
     'AXQ-2026-0001', 'Kestrel renewal commercial proposal', '66666666-6666-6666-6666-666666666601'::uuid,
     'SENT', 'NOT_REQUIRED', 94500.00::numeric, 12000.00::numeric, 82500.00::numeric, 38.5000::numeric, interval '21 days'),
    ('88888888-8888-8888-8888-888888888802'::uuid, '88888888-8888-8888-8888-888888888812'::uuid,
     'AXQ-2026-0002', 'Halden expansion draft quote', '66666666-6666-6666-6666-666666666602'::uuid,
     'DRAFT', 'NOT_REQUIRED', 186000.00::numeric, 18600.00::numeric, 167400.00::numeric, 42.0000::numeric, interval '30 days'),
    ('88888888-8888-8888-8888-888888888803'::uuid, '88888888-8888-8888-8888-888888888813'::uuid,
     'AXQ-2026-0003', 'Fenmore master agreement approval package', '66666666-6666-6666-6666-666666666607'::uuid,
     'IN_APPROVAL', 'PENDING', 410000.00::numeric, 82000.00::numeric, 328000.00::numeric, 28.0000::numeric, interval '14 days'),
    ('88888888-8888-8888-8888-888888888804'::uuid, '88888888-8888-8888-8888-888888888814'::uuid,
     'AXQ-2026-0004', 'Northbrook enterprise accepted quote', '66666666-6666-6666-6666-666666666608'::uuid,
     'ACCEPTED', 'APPROVED', 540000.00::numeric, 27000.00::numeric, 513000.00::numeric, 47.5000::numeric, interval '7 days')
  ) as s(id, group_id, quote_number, name, opportunity_id, status, approval_status,
         subtotal, discount_total, grand_total, margin_pct, expiry_interval)
)
insert into cpq.quote
  (id, tenant_id, quote_number, quote_group_id, version_number, is_active_version,
   opportunity_id, account_id, contact_id, price_book_id, owner_id, name, status,
   approval_status, currency_code, subtotal, discount_total, tax_total, grand_total,
   corporate_currency_code, corporate_grand_total, fx_rate, fx_rate_date, cost_total,
   margin_amount, margin_pct, quote_discount_pct, valid_from, expires_at, sent_at,
   accepted_at, document_ref, document_version, change_reason)
select s.id,
       o.tenant_id,
       s.quote_number,
       s.group_id,
       1,
       true,
       o.id,
       o.account_id,
       c.id,
       pb.id,
       o.owner_id,
       s.name,
       s.status,
       s.approval_status,
       'USD',
       s.subtotal,
       s.discount_total,
       0,
       s.grand_total,
       'USD',
       s.grand_total,
       1,
       current_date,
       round(s.grand_total * 0.62, 2),
       round(s.grand_total * (s.margin_pct / 100), 2),
       s.margin_pct,
       round((s.discount_total / nullif(s.subtotal, 0)) * 100, 4),
       current_date,
       now() + s.expiry_interval,
       case when s.status in ('SENT','ACCEPTED','REJECTED','ORDERED') then now() - interval '1 day' else null end,
       case when s.status = 'ACCEPTED' then now() else null end,
       case when s.status in ('SENT','ACCEPTED') then 'local://quotes/' || s.quote_number || '.pdf' else null end,
       case when s.status in ('SENT','ACCEPTED') then 1 else null end,
       'Seeded CPQ transaction for read-workspace verification.'
from quote_seed s
join sales.opportunity o on o.id = s.opportunity_id
join cpq.price_book pb on pb.tenant_id = o.tenant_id and pb.status = 'ACTIVE' and pb.is_default
left join lateral (
  select id from crm.contact c
  where c.tenant_id = o.tenant_id and c.account_id = o.account_id and c.deleted_at is null
  order by c.created_at
  limit 1
) c on true
on conflict (tenant_id, quote_number) do nothing;

insert into cpq.quote_line
  (tenant_id, quote_id, line_number, product_id, product_code, product_name,
   unit_of_measure, quantity, list_price, net_unit_price, extended_amount,
   discount_pct, discount_amount, pricing_method_applied, price_adjustments,
   unit_cost, cost_amount, margin_amount, margin_pct, currency_code,
   corporate_extended_amount, price_book_entry_id)
select q.tenant_id,
       q.id,
       1,
       p.id,
       p.code,
       p.name,
       p.unit_of_measure,
       50,
       e.unit_price,
       round(q.grand_total / 50, 4),
       q.grand_total,
       q.quote_discount_pct,
       q.discount_total,
       'LIST',
       jsonb_build_array(jsonb_build_object(
         'type', 'LIST_PRICE',
         'label', 'Seeded list price',
         'basisUnitPrice', e.unit_price,
         'resultingUnitPrice', round(q.grand_total / 50, 4)
       )),
       e.unit_cost,
       q.cost_total,
       q.margin_amount,
       q.margin_pct,
       q.currency_code,
       q.corporate_grand_total,
       e.id
from cpq.quote q
join cpq.product p on p.tenant_id = q.tenant_id and p.code = 'PLT-ADV'
join cpq.price_book_entry e on e.tenant_id = q.tenant_id and e.product_id = p.id and e.is_active
where q.quote_number in ('AXQ-2026-0001','AXQ-2026-0002','AXQ-2026-0003','AXQ-2026-0004')
on conflict (tenant_id, quote_id, line_number) do nothing;

insert into cpq.quote_line_adjustment
  (tenant_id, quote_line_id, sequence_no, adjustment_type, label, basis_unit_price,
   amount, resulting_unit_price, source_ref, detail)
select l.tenant_id,
       l.id,
       1,
       'LIST_PRICE',
       'Seeded list price',
       l.list_price,
       l.list_price,
       l.net_unit_price,
       l.price_book_entry_id::text,
       jsonb_build_object('seed', true)
from cpq.quote_line l
join cpq.quote q on q.tenant_id = l.tenant_id and q.id = l.quote_id
where q.quote_number in ('AXQ-2026-0001','AXQ-2026-0002','AXQ-2026-0003','AXQ-2026-0004')
on conflict (tenant_id, quote_line_id, sequence_no) do nothing;

insert into cpq.quote_approval
  (tenant_id, quote_id, policy_id, approval_type, reason, observed_value,
   threshold_value, shortfall, approver_role, approver_name, status, requested_by)
select q.tenant_id,
       q.id,
       p.id,
       'DISCOUNT',
       'Discount exceeds the seeded subscription approval threshold.',
       q.quote_discount_pct,
       p.threshold_pct,
       q.quote_discount_pct - p.threshold_pct,
       p.approver_role,
       'Sales Manager',
       'PENDING',
       q.owner_id
from cpq.quote q
join cpq.approval_policy p on p.tenant_id = q.tenant_id and p.code = 'DISC-15-SUBSCRIPTION'
where q.quote_number = 'AXQ-2026-0003'
on conflict (tenant_id, id) do nothing;

insert into cpq.quote_document
  (tenant_id, quote_id, quote_version_number, template_id, document_version,
   document_ref, file_name, content_type, byte_size, content_hash, content,
   is_executed_copy, generated_by, generated_by_name)
select q.tenant_id,
       q.id,
       q.version_number,
       dt.id,
       1,
       'local://quotes/' || q.quote_number || '.pdf',
       q.quote_number || '.pdf',
       'application/pdf',
       length(convert_to('Seeded quote artefact for ' || q.quote_number, 'UTF8')),
       encode(digest(convert_to('Seeded quote artefact for ' || q.quote_number, 'UTF8'), 'sha256'), 'hex'),
       convert_to('Seeded quote artefact for ' || q.quote_number, 'UTF8'),
       q.status = 'ACCEPTED',
       q.owner_id,
       u.display_name
from cpq.quote q
join cpq.document_template dt on dt.tenant_id = q.tenant_id and dt.code = 'STANDARD-QUOTE'
left join identity.app_user u on u.tenant_id = q.tenant_id and u.id = q.owner_id
where q.quote_number in ('AXQ-2026-0001','AXQ-2026-0004')
on conflict (tenant_id, quote_id, document_version) do nothing;
